#!/bin/bash
#Sofiane Hamlaoui

mute=$(pactl list sources | grep  "Mute: yes")
if [ "$mute" = "" ]; then
	notify-send -t 500 -i /home/sofiane/.icons/Flat-Remix-Blue-Dark/panel/audio-input-microphone-high-panel.svg 'Microphone Unmuted'
else
	notify-send -t 500 -i /home/sofiane/.icons/Flat-Remix-Blue-Dark/panel/audio-input-microphone-muted.svg 'Microphone Muted'
fi
