#!/bin/bash
#Sofiane Hamlaoui
# "on" if a jack cable is connected, off if not
# amixer -c 0 contents | grep "Front Headphone Jack" to check what NUMID you chose
headset=$(amixer -c 0 contents | \
awk -F"," '
$1 == "numid=13" {
    c=1
} c && /: values/ {
   split($0, a, "=")
   print a[2];
   exit
}')

# "" if capslock enabled
capslock=$(xset q | grep "Caps Lock:   on")

# "" if mic unmuted
mute=$(pactl list sources | grep  "Mute: yes")


if [ "$headset" = "on"  ]
then
	iconHeadset=
fi

if [ "$capslock" != "" ]
then
	iconCaps=
fi

if [ ! "$mute" = "" ]
then
	iconMute= 
fi

# icons output
echo "${iconCaps} ${iconHeadset} ${iconMute}"



